jwt:
  issuer: slothfkdla@gmail.com
  secret: oNlbC1SXEr6jig2XEvlZdhFULBbhukaY
logging:
  #file:
  #name: log/lotte.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: debug
    root: info
server:
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: a1s2d3F$
    url: jdbc:log4jdbc:mysql://13.209.17.103:3306/LomDDeock
    username: lombok
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  resources:
    static-locations: file:/C:/Users/Java/Desktop/Workspace/LotteON2/files/

  jpa:
    database: mysql
    hibernate:
      #ddl-auto: update
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 591789449e2da1495d41e7af46686eb7
            client-secret: 5sQauVk5ojt0TcSFY06Gz2fpW7YUCLxa
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    user:
      name: users
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 465
    username: 'oooq3o@gmail.com'
    password: 'nogwfaudlkjxyheh'
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      location: thumb/
      max-file-size: 10MB
upload:
  path:
    files: files/
    thumbs: thumbs/
    banners: banners/
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  version: 0.0.12-SNAPSHOT

filePath:
  #???
  #files: file:/C:/Users/JAVA2/Desktop/Workspace/lotte/files/
  #???
  #files: file:/C:/Users/Java/Desktop/Workspace/LotteON2/files/
  files: file:/home/LotteON/files/
  #???
  #thumbs: file:/C:/Users/JAVA2/Desktop/Workspace/lotte/thumbs/
  #???
  #thumbs: file:/C:/Users/Java/Desktop/Workspace/LotteON2/thumbs/
  #???
  #thumbs: file:/C:/Users/user/Desktop/Workspace/LotteON2/thumbs/
  thumbs: file:/home/LotteON/thumbs/
  #???
  #banners: file:/C:/Users/JAVA2/Desktop/Workspace/lotte/banners/
  #???
  #banners: file:/C:/Users/Java/Desktop/Workspace/LotteON2/banners/
  banners: file:/home/LotteON/banners/

  payment:
    toss:
      test_client_api_key : test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
      test_secret_api_key : test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
      success_url : "http://localhost:8080/api/v1/payments/toss/success"
      fail_url : "http://localhost:8080/api/v1/payments/toss/fail"